import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getRandomPrompt } from '../utils';
import { preview } from '../assets';
import { FormFiled,Loader } from '../components';

const CreatePost = () => {
  const navigate = useNavigate();
  const [form,setForm] = useState({
    name:'',
    prompt:'',
    photo:'',
  });
  const submitHandler = ()=>{

  }
  const changeHandler = (e) =>{

  }
  const supriseMeHandler = (e) =>{

  }
  // while making constact with backend api..
  const [generatingImg,setGeneratingImg] = useState(true);
  const[loading,setLoading] = useState(false);
  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>Create</h1>
        <p className = "max-w-[500px] mt-2 text-[16px] text-[#666e75]">Create imaginative and visually stunning images generated by AI ImageGenerator Community</p>
      </div>
      {/** Create post Compoent */}
      <form className= "mt-16 max-w-3xl" onSubmit={submitHandler}>
        <div className='flex flex-col gap-5'>
          <FormFiled 
          labelName = "Your name"
          type = "text"
          name = "name"
          placeholder = "Jonh Doe"
          value = {form.value}
          changeHandler = {changeHandler}
          />
          <FormFiled 
          labelName = "Prompt"
          type = "text"
          name = "prompt"
          placeholder = "A plush toy robot sitting against a yellow wall"
          value = {form.prompt}
          changeHandler = {changeHandler}
          isSuprisseMe
          supriseMeHandler = {supriseMeHandler}
          />
          {/**just showing the image which are getting generated incase Nothing them show the default image.*/}
          <div className='relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center'>
            {form.photo?(<img src = {form.photo} alt = {form.prompt} className='w-full h-full object-contain'/>):(<img src = {preview} alt = "preview" className='w-9/12 h-9/12 object-contain opacity-40'/>)
            }
          {generatingImg && <div className='absolute inset-0 z-0 flex justify-center items-center bg-[rgbs(0,0,0,0.5)] rounded-lg'>
            <Loader />
            </div>}
          </div>
        </div>
      </form>
    </section>
  )
}

export default CreatePost;